BookStore/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("admin")]
    [Route("admin")]
    public class HomeController : Controller
    {
        [Route("")]
        // GET: HomeController
        public ActionResult Index()
        {
            return View();
        }

        [Route("details/{id}")]
        // GET: HomeController/Details/5
        public ActionResult Details(int id)
        {
            return View(id);
        }

        [Route("create")]
        // GET: HomeController/Create
        public ActionResult Create()
        {
            return View();
        }
        [Route("create")]
        // POST: HomeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        [Route("edit")]
        // GET: HomeController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }
        [Route("edit")]
        // POST: HomeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        [Route("delete")]
        // GET: HomeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HomeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BookStore/Areas/Financial/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Areas.Financial.Controllers
{
    [Area("Financial")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BookStore/Components/TopBooksViewComponent.cs
using BookStore.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Components
{
    public class TopBooksViewComponent : ViewComponent
    {
        private readonly IBookRepository _bookRepository;
        public TopBooksViewComponent(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository; 
        }
        public async Task<IViewComponentResult> InvokeAsync(int count)
        {
            var books = await _bookRepository.GetTopBooksAsync(count);
            return View(books);
        }
    }
}

BookStore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Dynamic;
using BookStore.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using BookStore.Repository;
using BookStore.Service;
using Microsoft.AspNetCore.Authorization;

namespace BookStore.Controllers
{
    //[Route("[controller]/[action]")]
    public class HomeController : Controller
    {
        private readonly NewBookAlertConfig _newBookAlertconfiguration;
        private readonly NewBookAlertConfig _thirdPartyBookconfiguration;
        private readonly IMessageRepository _messageRepository;
        private readonly IUserService _userService;
        private readonly IEmailService _emailService;

        /* [ViewData]
           public string Title { get; set; }
           [ViewData]
           public BookModel book { get; set; }*/

        public HomeController(IOptionsSnapshot<NewBookAlertConfig> newBookAlertconfiguration,
            IMessageRepository messageRepository, IUserService userService, IEmailService emailService)                                                                                /*here we are injecting the confi service(Binding conf using Ioption) include model class into constr along with the singleton service(IMessageRepository) and binding the values in below lines*/            
        {
            _newBookAlertconfiguration = newBookAlertconfiguration.Get("InternalBook");
            _thirdPartyBookconfiguration = newBookAlertconfiguration.Get("ThirdPartyBook");
            _messageRepository = messageRepository;
            _userService = userService;
            _emailService = emailService;
        }

        //[Route("")]
        public async Task<ViewResult> Index()
        {

            //this code done here for testing perpose but used this code to send an email to verify user. in sendemailconfirmationmail method in accountreposty file. code is till await line
            //UserEmailOptions options = new UserEmailOptions                                                                                               /*here by creating instance of UserEmailOption cls we Wrote some logic here*/
            //{
            //    ToEmails = new List<string>() { "meme@gmail.com"},                                                                                          /*we are using fake smtp credentials from mailtrap site so whatever emails we write here will go to mailtrap site*/
            //    PlaceHolders = new List<KeyValuePair<string, string>>()                                                                                      /*by using this we can pass or send dynamic content in mails. this done by using placholder property and updateplaceholder method in respective clss*/
            //    {
            //        new KeyValuePair<string, string>("{{UserName}}", "Tester")
            //    }
            //};

            //await _emailService.SendTestEmail(options);                                                                                                    /*here we are calling  public SendTestEmail method from EmailSrvice cls by passing above cls instance*/

            //var userId = _userService.GetUserId();                                                                                                        /*here we are using GetUserId method(of UserService cls) by injecting the service into constructor*/
            //var isLoggedIn = _userService.IsAuthenticated();                                                                                              /*same as above line from same cls. from above line we are getting the loggedinuser Id and from this we get to know the user logged in or not*/

            /*var value = _messageRepository.GetName(); */                                                                                                   /*here we getting value from messagerepository these are for just check wether value coming or not*/
            //bool isDisplay = _newBookAlertconfiguration.DisplayNewBookAlert;
            //bool isDisplay1 = _thirdPartyBookconfiguration.DisplayNewBookAlert;

            //var newBookAlert = new NewBookAlertConfig();                                                                                               /*Binding configuration to objects using bind method appsetting.json.to map the properties of an obj to obj of model*/
            //configuration.Bind("NewBookAlert", newBookAlert);

            //var newBook = configuration.GetSection("NewBookAlert");
            //var result1 = newBook.GetValue<bool>("DisplayNewBookAlert");                                                                                  /*here we using configuration with section by doing this no need to write field name and obj name(obj in Json file)means no repitation. see diff b/w below and this line*/
            //var result2 = configuration.GetValue<string>("NewBookAlert:BookName");
            //var result = configuration["AppName"];       
            //var key1 = configuration["infoObj:key1"];
            //var key2 = configuration["infoObj:key2"];
            //var key3 = configuration["infoObj:key3:key3Obj1"];
            return View();
        }

        [Route("About-us")]
        public ViewResult Aboutus()
        {
            return View();
        }
        [Authorize(Roles ="Admin")]
        public ViewResult Contactus()
        {
            return View();
        }
    }
}

BookStore/Views/Home/Aboutus.cshtml
@{ 
    ViewData["HeadTitle"] = "About us";
}
   <h2>This is about books and its aplication</h2>

BookStore/Views/Home/Contactus.cshtml
@{ 
    ViewData["HeadTitle"] = "Contact us";
}
    <h1>Please contact us</h1>

BookStore/Views/Home/Index.cshtml
@*@{
        dynamic data = ViewBag.Data;//for viewBag here we have mention the dynamic data type for complex viewBag code like using viewBag in BookModel data type
        var Bookinfo = ViewData["Book"] as BookModel;//for viewData here we have cast the data and datatype for complex viewData code like using viewData in BookModel data type

    }*@
@{
    //var look = ViewData["book"] as BookModel;
    ViewData["HeadTitle"] = "Home";
}
@inject BookStore.Repository.IBookRepository _bookRepository


<section class=" jumbotron text-center">
    <div class="container">
        <h1>WELCOME TO BOOKSTORE</h1>
        <p>

            @*  @data.Id <br />
                @data.Name <br />
                Id=@ViewBag.Type.Id <br />
                Name = @ViewBag.Type.Author<br />


                Id=@Bookinfo.Id <br />
                Name= @Bookinfo.Author<br />
                    @ViewData["Title"] <br />
                    Id = @look.Id <br />
                    Name = @look.Author <br />*@

            This is a book apllication here you get all kind of books.
            whatever you want can order through this website
        </p>
        <p>
            <a href="#" class=" btn btn-primary">Search books</a>
        </p>
    </div>
</section>


<div class="container">
    <h3 class="h3">Top Books</h3>
    @*<big>Top Books</big>*@                                                                                               @*here (both lines) we are overriding the existing html(big tag) using bigtaghelper.cs class.*@
    @*<p big>Top Books using Attribute</p>*@

    @await Component.InvokeAsync("TopBooks", new { count = 3})                                                             @*these two lines(two ways of using components on view) are from view components(default.cshtml and Topbookviewcomponent file) rendering data or (data from db) using view components.latest included parameter(we can pass n parameters)*@
    @*<vc:top-books count="3"></vc:top-books>*@

    
</div>


@*@section script1{
    <script>
        $(document).ready(function () {
            //alert("document is ready");
        })
    </script>
}*@